### PR TITLE
fixed black rendering on some faces with some placements of slopes and corners

### LINKED ISSUE #3: Slants have black texture errors at certain positions
Forge: 14.23.4.2756 (MC 1.12.2)
Blockcraftery: 0.1.3

Other than placing the blocks in the shown orientations (error occurs whether they are given a block or not), I don't have anything special to reproduce it.

### PR DESCRIPTION
**Pull request by SanAndreasP**
fixes #3
requires EpicSquid/MysticalLib#6

### CODE REVIEW

**Comment by EpicSquid** [comment]
Two questions: what does "makesegmup" do? (can you add comments for that) and why is the forge version being updated?

**Comment by SanAndreasP** [comment]
I can add some comments, sure.
The makeSegmUp is a special version of the makeSegm method where every face except the downward one has its first and second coord switched with its third and fourth. This is because just merely switching around coords in the method calls themselves won't work (like the sideways slant where either the top or the bottom face is black)
For some reason faces are rendered black on custom baked models if the coords have a "wrong drawing order" on newer Forge versions, thus this bug only occurring recently.
That's also why I've updated the Forge version.

**Comment by SanAndreasP** [comment]
The forge version isn't required, it's just determining which version the dev environment is running.
There's no mention of any forge dependency here: https://github.com/EpicSquid/Blockcraftery/blob/master/src/main/java/epicsquid/blockcraftery/Blockcraftery.java#L19

But I can change it back to be the original version, it shouldn't matter anyway.


PS: all of the mods that are broken have been updated AFAIK, so users can update now.

**Comment by EpicSquid** [comment]
Awesome thanks for the psa. I'll merge this asap

**Comment by SanAndreasP** [comment]
I've added comments now :)

**Comment by EpicSquid** [comment]
Awesome thank you. Hopefully I can distribute this soon. Just a few more updates to do :D

**Pull request merged**
